# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.network "private_network", ip: "192.168.33.20"
    server.vm.network "public_network"
    server.vm.network "forwarded_port", guest: 80, host: 8080


    server.vm.synced_folder ".", "/app/code"
    server.vm.provider "vmware_desktop" do |vm|
      vm.vmx["memsize"] = "2048"
      vm.vmx["numvcpus"] = "1"
    end
    server.vm.provision "shell", path:"provision.sh"
  end
  config.vm.define "client" do |client|
    client.vm.box = "bento/ubuntu-22.04"
    client.vm.network "private_network", ip: "192.168.33.30"
    client.vm.provider "vmware_desktop" do |vm|
      vm.vmx["memsize"] = "2048"
      vm.vmx["numvcpus"] = "1"
    end
  end
end

